// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiEunsQcCJR9BMOS-4Yat6__t3lYQbBx0',
    appId: '1:984091495329:web:3a660e72a53a4f690819e0',
    messagingSenderId: '984091495329',
    projectId: 'upshot-platform',
    authDomain: 'upshot-platform.firebaseapp.com',
    storageBucket: 'upshot-platform.appspot.com',
    measurementId: 'G-T6FTPVQQHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIdmyweBZhx6wLCnqZDciQnyFpI7-dy4',
    appId: '1:984091495329:android:f5f76611b0f21ff10819e0',
    messagingSenderId: '984091495329',
    projectId: 'upshot-platform',
    storageBucket: 'upshot-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpgLOPW60aIn5GTQzPGi9ci_68Lm_9S4',
    appId: '1:984091495329:ios:d8c71f8b775015990819e0',
    messagingSenderId: '984091495329',
    projectId: 'upshot-platform',
    storageBucket: 'upshot-platform.appspot.com',
    iosClientId: '984091495329-rc2nj5su8sqi9h3mgau0jcpvel28deut.apps.googleusercontent.com',
    iosBundleId: 'com.example.upshotFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIpgLOPW60aIn5GTQzPGi9ci_68Lm_9S4',
    appId: '1:984091495329:ios:d8c71f8b775015990819e0',
    messagingSenderId: '984091495329',
    projectId: 'upshot-platform',
    storageBucket: 'upshot-platform.appspot.com',
    iosClientId: '984091495329-rc2nj5su8sqi9h3mgau0jcpvel28deut.apps.googleusercontent.com',
    iosBundleId: 'com.example.upshotFlutter',
  );
}
